spring.application.name=storefront-service
server.port=8080
spring.mongodb.uri=mongodb://localhost:27017/petstore_storefront?replicaSet=rs0
spring.data.mongodb.auto-index-creation=true
logging.level.com.mdb.petstore=DEBUG
petstore.order-processing.base-url=http://localhost:8081
petstore.order-processing.connect-timeout=3s
petstore.order-processing.read-timeout=5s
